export const TODO_LIST_PENDING = 'TODO_LIST_PENDING';
export const TODO_LIST_FETCHED = 'TODO_LIST_FETCHED';
export const TODO_LIST_ERROR = 'TODO_LIST_ERROR';
export const TODO_LIST_CLEAR = 'TODO_LIST_CLEAR';
